apiVersion: v1
kind: Service
metadata:
  name: micro-order
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-order
  ports:
  - name: micro-order
    port: 8006
    targetPort: 8006
    protocol: TCP
