apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: micro-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25% # The max number of newly created pods above my replica number
      maxUnavailable: 25% # The maximum number of pods that could not be available of my replicas number 
  template:
    metadata:
      labels:
        app: micro-api
    spec:
      containers:
      - name: micro-api
        image: ahmadki/micro-api:stable
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "150Mi"
            cpu: "100m"
        ports:
        - name: micro-api
          containerPort: 8000
        env:
        - name: GATEWAY_JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: gateway-jwt-token

        - name: JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-token

        - name: ELASTIC_SEARCH_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: elastic-search-url

        - name: AUTH_BASE_URL
          value: 'http://micro-auth.production.svc.cluster.local:8002'
          
        - name: USERS_BASE_URL
          value: 'http://micro-users.production.svc.cluster.local:8003'
          
        - name: GIG_BASE_URL
          value: 'http://micro-gig.production.svc.cluster.local:8004'
          
        - name: MESSAGE_BASE_URL
          value: 'http://micro-chat.production.svc.cluster.local:8005'
          
        - name: ORDER_BASE_URL
          value: 'http://micro-order.production.svc.cluster.local:8006'
          
        - name: REVIEW_BASE_URL
          value: 'http://micro-review.production.svc.cluster.local:8007'
          
        - name: PORT
          value: "8000"