apiVersion: v1
kind: Service
metadata:
  name: micro-users
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-users
  ports:
  - name: micro-users
    port: 8003
    targetPort: 8003
    protocol: TCP
