apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-local-storage
  hostPath:
    path: "/storage/data1" 