apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: micro-redis
  namespace: production
spec: # The spec for the stateful set itself.
  serviceName: jobber-redis # The name of the service 
  replicas: 1
  selector:
    matchLabels:
      app: micro-redis # Must Match the service spec.selector or the statful set validation will fail.
  template: # Each pod will be created using this template
    metadata:
      labels:
        app: micro-redis # so the service will be attached to each pod has this name.
    spec: # The Spec for the Template of the statful set.
      initContainers:
      - name: config
        image: redis:alpine
        command: [ "sh", "-c" ]
        args:
          - |
            cp /tmp/redis/redis.conf /etc/redis/redis.conf
            
            echo "finding master..."
            MASTER_FQDN=`hostname  -f | sed -e 's/jobber-redis-[0-9]\./jobber-redis-0./'`
            if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
              echo "master not found, defaulting to jobber-redis-0"

              if [ "$(hostname)" == "jobber-redis-0" ]; then
                echo "this is jobber-redis-0, not updating config..."
              else
                echo "updating redis.conf..."
                echo "slaveof $MASTER_FQDN 6379" >> /etc/redis/redis.conf
              fi
            else
              echo "sentinel found, finding master"
              MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^jobber-redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
              echo "master found : $MASTER, updating redis.conf"
              echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
            fi
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/
      containers:
      - name: micro-redis
        image: redis:alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: micro-redis 
        readinessProbe: # Check if the container ready to accept traffic.
          periodSeconds: 10
          tcpSocket:
            port: micro-redis # It refers to the port name we defined in ports.
        livenessProbe: # Check if the Container is still Running.
          periodSeconds: 10
          tcpSocket:
            port: micro-redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "redis-local-storage"
      resources:
        requests:
          storage: 500Mi