apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-postgres
  template:
    metadata:
      labels:
        app: micro-postgres
    spec:
      containers:
      - name: micro-postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: 0938460904am
        - name: POSTGRES_DB
          value: review_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: micro-postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-local-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "review_db", "-c", "SELECT 1"]
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "review_db", "-c", "SELECT 1"]
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
      volumes:
      - name: postgres-local-storage
        persistentVolumeClaim:
          claimName: postgres-pvc