apiVersion: v1
kind: Service
metadata:
  name: micro-queue
  namespace: production
spec:
  type: NodePort
  selector:
    app: micro-queue
  ports:
  - name: micro-queue
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: queue-mgmt
    port: 15672
    targetPort: 15672
    protocol: TCP
