apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production 
type: Opaque
data:
  gateway-jwt-token: 
  jwt-token: 
  micro-redis-host: 
  secret-key:   
  auth-base-url: 
  users-base-url: 
  gigs-base-url: 
  message-base-url: 
  order-base-url: 
  reviews-base-url: 
  elastic-search-url: 
  elastic-search-host: 
  elastic-search-password:   
  rabbitmq-url: 
  stripe-api-key: 
  mysql-host: 
  mysql-port: 
  mysql-user: 
  mysql-database: 
  mysql-password: 
  cloud-name: 
  cloud-api-key: 
  cloud-api-secret: 
  mongo-host: 
  mongo-port: 
  mongo-database: 
  postgres-host: 
  postgres-user: 
  postgres-password: 
  postgres-port: 
  postgres-database: 
