apiVersion: v1
kind: Service
metadata:
  name: micro-chat
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-chat
  ports:
  - name: micro-chat
    port: 8005
    targetPort: 8005
    protocol: TCP
