apiVersion: v1
kind: Service
metadata:
  name: micro-review
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: micro-review
  ports:
  - name: micro-review
    port: 8007
    targetPort: 8007
    protocol: TCP
